language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
services:
- mongodb
deploy:
  provider: heroku
  app: empresas-cc
  api_key:
    secure: AsqQi7jAEtM1RbfKh/ZrHaG9DVRR7wFubNf97YJ19bznRZ4O2LiHDQ7qm9ECUr6TrX8NzMtpdnWdNi+2MLg75YJCZU78FdE/C3wQAWhv6Cf00mnNF4ZouH5EGFe006lMliTFg/jMJrjOXlYDPEQ02cgnMg9YDRbGHPE7Tb9q0+e5UT2keAQpq+xxeSWhUOsWdUqYp0/NrA0Ax2zbMcoTyF4L2gmagL+/A3sJgKaeDtc2qa1pXJ4BLMKc9r3XA7TB/+EX8RdDNi2OYokQY64LagjNv6Sl1oxoXwIMOlySV6DHm+INbgE6JW/FbK/RTPDdVi/Pr4iaL0Sn1/DlnJIfz1lkG71xjsFtTbZBbQoGurOtjebYIQB0kos7gqhtUiW/ytB8dLfKZ8huz31KuIol2jXy2j5mD1jCoH9fVygLSJ8o2enqYFH6I4VB12F2RZcjFZb55+jubb/3i2h8BLH76tonLOR3T4jXAasQAvtBj+nf0GxDT8GgXAm0rCCjgttdtkJ/oUG1YwzFvhCetoQBRWmnj4yZw6cL8uFFgVTVgJ2sDeSgirrKXG2hJZx4eHO4V5Ha0TW+MGN+yKYgm56f729sSE/8sFzHu7msSEL7ifmGRLZ4rUhg9MGVOqRdTZU95iwmzKd9aXD1FljNjNAci9BPPQbjVPBA28hMpG12tG8=